### ISSUE TITLE
Extend Autorole to all servers

### ISSUE THREAD

**Issue by AdityaJain1030** [enigmadigm/GreenMesa#279]
**Is your feature request related to a problem? Please describe.**
Autorole only works for one server

**Describe the solution you'd like**
Adding a table and maybe just parse that for autorole servers?

**Describe alternatives you've considered**
Adding another bot

**Additional context**
n/a feature request also made on discord

**Comment by GalaxySH** [comment]
awknowledged

**Comment by GalaxySH** [comment]
Option on the dashboard.
